"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.adminRouter = void 0;
const express_1 = require("express");
const AdminController_1 = require("../controller/AdminController");
const adminMiddleware_1 = require("../middleware/adminMiddleware");
const authMiddleware_1 = require("../middleware/authMiddleware");
const adminRouter = (0, express_1.Router)();
exports.adminRouter = adminRouter;
const adminController = new AdminController_1.AdminController();
adminRouter.get('/', authMiddleware_1.authMiddleware, adminMiddleware_1.adminMiddleware, adminController.enter);
